/**
 * Legacy config — sitemap output is generated by `scripts/generate-sitemaps.mjs`
 * (see package.json `postbuild`). Kept for reference; next-sitemap is not run in CI.
 */
/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://houznext.com',
  generateRobotsTxt: false,
  changefreq: 'weekly',
  priority: 0.7,
  exclude: [],
}
